name: Test

on: [push, pull_request]

jobs:
    rules:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/cache@v4
              with:
                  path: ~/.cache/bazelisk
                  key: ${{ runner.os }}--${{ hashFiles('**/.bazelversion') }}
            - uses: bazelbuild/setup-bazelisk@v3
            - run: bazel build //:all

    examples:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/cache@v4
              with:
                  path: ~/.cache/bazelisk
                  key: ${{ runner.os }}--${{ hashFiles('**/.bazelversion') }}
            - uses: bazelbuild/setup-bazelisk@v3
            - run: ./.github/workflows/install.sh
            - run: make -C examples
